# agents/editor_agent.py
import google.generativeai as genai
from agents.base_agent import BaseAgent
from configs.settings import GEMINI_API_KEY

class EditorAgent(BaseAgent):
    """Uses Gemini to polish summaries to academic publishing standards."""

    def __init__(self):
        genai.configure(api_key=GEMINI_API_KEY)
        self.model = genai.GenerativeModel("gemini-1.5-flash")

    def execute(self, input_data: str, topic: str) -> str:
        prompt = (
            "You are the Editor Agent in a CrewAI multi-agent research assistant system called ResearchMate.\n"
            "Your task is to polish and finalize the draft research report generated by the Summariser Agent.\n\n"
            "Edit to improve grammar, clarity, coherence, consistency, academic tone, and logical flow.\n"
            "Preserve the report's structure, headings, and references.\n"
            "Strictly follow these rules:\n"
            "- Do NOT change the section headings or their order.\n"
            "- Do NOT use tables anywhere.\n"
            "- Do NOT add or remove references.\n"
            "- The References section must remain a clean, single-line numbered list matching the article titles provided.\n"
            "- Maintain inline numbered citations as [1], [2], etc.\n"
            "- Keep each reference on a single line.\n\n"
            f"{input_data}"
        )
        response = self.model.generate_content(prompt)
        return response.text
